# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{
font_family JetBrains Mono Regular
bold_font JetBrains Mono SemiBold
italic_font JetBrains Mono Italic
bold_italic_font JetBrains Mono SemiBold Italic
font_size 13.0

# Nerd Font symbol maps
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A2,U+E0A3,U+E0B0-U+E0B3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E600-U+E6C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F372,U+F400-U+F532,U+F0001-U+F1AF0 Hack Nerd Font Mono
symbol_map U+E74E,U+E77B,U+E71E Hack Nerd Font Mono
#: }}}

#: Scrollback {{{
scrollback_lines 20000
#: }}}

#: Terminal bell {{{
enable_audio_bell no
#: }}}

#: Window layout {{{
enabled_layouts splits
window_margin_width 3
window_padding_width 5
inactive_text_alpha 0.3
#: }}}

#: Tab bar {{{
tab_bar_style slant
tab_bar_align left
tab_bar_min_tabs 1
tab_powerline_style slanted
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title} ({tab.active_oldest_exe})"
#: }}}

#: Advanced {{{
allow_remote_control socket-only
#: }}}

#: Cursor {{{
cursor_trail 50
#: }}}

#: Keyboard shortcuts {{{

# Scrollback search via fzf
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /opt/homebrew/bin/fzf --no-sort --no-mouse --exact -i

# Window navigation
map cmd+] next_window
map cmd+[ previous_window
map cmd+` move_window_to_top

map ctrl+h neighboring_window left
map cmd+left neighboring_window left
map ctrl+l neighboring_window right
map cmd+right neighboring_window right
map ctrl+j neighboring_window down
map cmd+down neighboring_window down
map ctrl+k neighboring_window up
map cmd+up neighboring_window up

# Window management
map cmd+d launch --location=vsplit
map cmd+shift+d launch --location=hsplit
map cmd+w close_window

map cmd+f7 focus_visible_window
map cmd+f8 swap_with_window

# Window moving
map cmd+shift+left move_window left
map cmd+shift+right move_window right
map cmd+shift+down move_window down
map cmd+shift+up move_window up

# Search kitten
# for details: https://github.com/trygveaa/kitty-kitten-search
map cmd+f launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

#: }}}

# Theme
include current-theme.conf
