format = """
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
[](fg:prompt_bg_color)\
$fill\
[](fg:prompt_bg_color)\
$time\
${env_var.FLASK_RUN_PORT}\
$aws\
$python\
$ruby\
$golang\
$kubernetes\
$battery\
$memory_usage\
$line_break\
$cmd_duration\
$character\
"""

palette = "main"

[palettes.main]
white = "#ffffff"
red = "#c90011"
blue = "#0087AF"
yellow = "#574400"


prompt_bg_color = "#303030"
separator_color = "#ffffff"
character_color = "#5FD700"
fill_color = "#3d3d3d"

git_repo_root_color = "#00AFFF"
git_branch = "#5FD700"

python_color = "#00AFAF"
ruby_color = "#B31209"
go_color = "#00ACD7"
kube_color = "#326CE5"
aws_color = "#FF9900"
cmd_duration = "#87875F"
kubernetes_color = "#326CE5"

# general
[line_break]
disabled = false

[character]
success_symbol = "[❯](bold character_color)"
error_symbol = "[❯](bold red)"

[cmd_duration]
min_time = 500
format = ' [$duration](cmd_duration) '

[fill]
symbol = "┄"
style = 'fill_color'

# left prompt

[username]
show_always = true
style_user = "bg:prompt_bg_color"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = true

[os]
style = "fg:white bg:prompt_bg_color"
disabled = false # Disabled by default

[os.symbols]
Macos = " "

[directory]
style = "bg:prompt_bg_color fg:blue bold"
before_repo_root_style = "bg:prompt_bg_color fg:blue"
truncate_to_repo = true
repo_root_style = "bg:prompt_bg_color git_repo_root_color"
read_only_style = "bg:prompt_bg_color"
repo_root_format = '[  $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only ]($read_only_style)'
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
always_show_remote = false
truncation_length = 30
style = "bg:prompt_bg_color fg:git_branch"
format = '[](bg:prompt_bg_color fg:separator_color)[ $symbol $branch(:$remote_branch) ]($style)'

[git_state]
style = "bold fg:yellow bg:prompt_bg_color"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
style = "bg:prompt_bg_color"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format ="([\\[$all_status$ahead_behind\\] ]($style))"

[git_metrics]
disabled = false
added_style = "bold fg:green bg:prompt_bg_color"
deleted_style = "bold fg:red bg:prompt_bg_color"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'


# right prompt
[aws]
disabled = false
force_display = true
style = "bg:prompt_bg_color"
format = '[](fg:separator_color bg:prompt_bg_color)[ $symbol($profile )(\($region\) )(\[$duration\] )]($style)'
region_aliases = {"us-west-2"="us", "eu-west-1"="eu"}

[kubernetes]
disabled = false
style = 'bg:prompt_bg_color fg:kubernetes_color'
format = '[](fg:separator_color bg:prompt_bg_color)[ $symbol$context ]($style)'
# detect_folders = ["work"]

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:prompt_bg_color"
format = '[  $time ]($style)'

[python]
symbol = ""
style = "bg:prompt_bg_color fg:python_color"
format = '[](fg:separator_color bg:prompt_bg_color)[ $symbol ($version) ]($style)'

[ruby]
symbol = "💎"
style = "bg:prompt_bg_color"
format = '[](fg:separator_color bg:prompt_bg_color)[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:prompt_bg_color fg:go_color"
format = '[](fg:separator_color bg:prompt_bg_color)[ $symbol ($version) ]($style)'

[env_var.FLASK_RUN_PORT]
variable = "FLASK_RUN_PORT"
symbol = "🍼 "
style = "bg:prompt_bg_color white dimmed"
format ="[](fg:separator_color bg:prompt_bg_color)[ $symbol$env_value ]($style)"
description = "Port on which flask server will be started"

[battery]
disabled = false
format = "[](fg:separator_color bg:prompt_bg_color)[ $symbol$percentage ]($style)"
# full_symbol = '🔋'
# charging_symbol = "🔥 "

[[battery.display]]
style = "bg:prompt_bg_color"
threshold = 60

[[battery.display]]
style = "bg:prompt_bg_color fg:yellow"
threshold = 40

[[battery.display]]
style = "bg:prompt_bg_color fg:red"
threshold = 20

[memory_usage]
disabled = false
threshold = 10
symbol = " "
style = "bg:prompt_bg_color"
format ="[](fg:separator_color bg:prompt_bg_color)[ $symbol $ram_pct(| $swap_pct)]($style) "
