[tools]
python = "latest"
golang = "latest"
sqlite = "3.40.1"
httpie-go = "latest"
awscli = "2.15.8"
ruby = "2.7.8"
terraform = "1.3.7"
deno = "1.30.0"
shellcheck = "0.9.0"
helm = "3.8.1"
nodejs = "18.13.0"
go = "latest"
node = "20"
just = "latest"
usage = "latest"

[alias]

[alias.python]
"3.12" = "3.12.3"
"3.11" = "3.11.7"
"3.10" = "3.10.9"
