[settings]
# whether to prompt to install plugins and runtimes if they're not already installed
missing_runtime_behavior = 'warn' # other options: 'ignore', 'warn', 'prompt', 'autoinstall'
legacy_version_file = true
experimental = true
shims_dir = "/Users/del-boy/.local/share/rtx/shims"
trusted_config_paths = ["~/work"]
raw = true

[tools]
python = "latest"
golang = "latest"
sqlite = "3.40.1"
httpie-go = "latest"
awscli = "2.9.19"
ruby = "2.7.6"
terraform = "1.3.7"
deno = "1.30.0"
shellcheck = "0.9.0"
helm = "3.8.1"
kubectl = "1.26.1"
mongosh = "latest"
rust = "1.67.0"
hugo = "extended_0.110.0"
nodejs = "18.13.0"

[alias]

[alias.python]
"3.10" = "3.10.9"
"3.11" = "3.11.1"
